title: cyberybrain
description: "a really cool jerkll theme that is stylish and cool."
encoding: utf-8
enable_dark_theme: "true"
exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]